spring:
  application:
    name: rabbitmq-server
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    listener:
      simple:
        auto-startup: true  # ? ??? ?? ? ???? ??? ??? ??

server:
  port: 8090
rabbitmq:
  queue: sample-queue
  exchange: sample-exchange
  routing-key: sample.key