version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # ✅ 관리 UI 포함된 RabbitMQ 사용
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP 프로토콜 포트
      - "15672:15672" # 관리 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
